#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'git'
cookbook 'mongodb'
cookbook 'nodejs'
cookbook 'deploy_key'
cookbook 'root_ssh_agent',
	:git => 'git@github.com:dergachev/chef_root_ssh_agent.git'

#cookbook 'iptables-ng',
#	:git => 'git@github.com:chr4-cookbooks/iptables-ng.git'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
